name: CI

on:
  push:
    branches: ["Lab4"]
  pull_request:
    branches: ["Lab4"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEXTAUTH_SECRET: test
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: "file:./dev.db"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Setup Prisma
        run: |
          npx prisma generate
          npx prisma db push

      - name: Run Jest tests
        run: npm run test

      - name: Run coverage
        run: npm run test:coverage

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build

      - name: Start app
        run: npm run start &

      - name: Wait for app
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: npm run test:e2e